# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_data',
            name='followup',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer_data',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Confirm'), (2, 'Rejected')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle_selected_data',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
