# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0003_user_data_first_time_user'),
        ('customer', '0002_auto_20170409_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_data',
            name='dse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add_user.dse_data'),
        ),
    ]
