# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20170411_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_data',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirm'), (2, 'Rejected')], default=0),
        ),
    ]
