# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dealer_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('location', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='dse_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='dsm_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add_user.dealer_data')),
            ],
        ),
        migrations.CreateModel(
            name='tsm_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(default=b'd8022f2060ad6efd297ab73dcc5355c9b214054b0d1776a136a669d26a7d3b14f73aa0d0ebff19ee333368f0164b6419a96da49e3e481753e7e96b716bdccb6f', max_length=1200)),
                ('fcm', models.CharField(blank=True, max_length=400, null=True)),
                ('designation', models.CharField(choices=[('-1', 'None'), ('2', 'DSE'), ('1', 'DSM'), ('0', 'TSM')], max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(default='/media/users/default.png', upload_to='users/')),
                ('active', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tsm_data',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add_user.user_data'),
        ),
        migrations.AddField(
            model_name='dsm_data',
            name='tsm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add_user.tsm_data'),
        ),
        migrations.AddField(
            model_name='dsm_data',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add_user.user_data'),
        ),
        migrations.AddField(
            model_name='dse_data',
            name='dsm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add_user.dsm_data'),
        ),
        migrations.AddField(
            model_name='dse_data',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add_user.user_data'),
        ),
    ]
