# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-25 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='profile',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
