# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-25 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='designation',
            field=models.CharField(choices=[('None', 'None'), ('DSE', 2), ('DSM', 1), ('TSM', 0)], default='None', max_length=400),
        ),
    ]
