# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-08 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0002_auto_20170408_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='first_time_user',
            field=models.BooleanField(default=True),
        ),
    ]
