# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-25 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0002_auto_20170125_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='designation',
            field=models.CharField(choices=[('None', 'None'), (0, 'DSE'), (1, 'DSM'), (2, 'TSM')], default='None', max_length=400),
        ),
    ]
