# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-25 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0003_auto_20170125_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='designation',
            field=models.IntegerField(choices=[('None', 'None'), (0, 'DSE'), (1, 'DSM'), (2, 'TSM')]),
        ),
    ]
