# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0003_user_data_first_time_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsm_data',
            name='target_daily_dse',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dsm_data',
            name='terget_monthly_dsm',
            field=models.IntegerField(default=0),
        ),
    ]
