# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0005_auto_20170413_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='dse_data',
            name='customer_reached_today',
            field=models.IntegerField(default=0),
        ),
    ]
