# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0006_dse_data_customer_reached_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='dse_data',
            name='tagret_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
