# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0007_dse_data_tagret_achieved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsm_data',
            name='total_customer_this_month',
        ),
    ]
